### ISSUE TITLE
Landscape mode on mobile inefficient 

### ISSUE THREAD

**Issue by j-cop** [007joshie/npbhs_map#4]
When I flip my phone to landscape, there is very little room to navigate the map
A solution to this could be a menu drawer or making the title retreat after a short period of time to free up space.
Thanks

**Comment by 007joshie** [comment]
The problem with your suggestion is the NPBHS Logo is used as a viewport reset button and If hidden, Cannot be activated.
Will come up with a solution in the near future...

**Comment by 007joshie** [comment]
Not a priority. Maybe one day....
